# Generated by Django 6.0 on 2025-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tarefa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
