# Generated by Django 6.0 on 2025-12-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarefa_prazo_tarefa_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='deletada',
            field=models.BooleanField(default=False),
        ),
    ]
